---
title: "Assignment B1"
author: "Maithili Devadas"
date: "2022-11-04"
output: github_document
---

```{r}
#Loading packages 
library(devtools)
library(usethis)
library(tidyverse)
library(testthat)
library(datateachr)
library(palmerpenguins)
```

***Exercise 1 and 2: Making and documenting a function**
```{r}
#For the cancer dataset I previously worked on, I repeated the commands for making summary statistic tables multiple times for different variables. At the time, I did not know how to create a function. Thus, I would like to create a function that calculates a few summary statistics for example, the mean and the median for variables in my dataset.

#The function here first recognizes whether the input is numeric or not. If it is not numeric, R #returns with an error. If the input is numeric, the function computes its mean and median

MeanandMedian<- function(data) {
  if(!is.numeric(data)){
    stop("The following function cannot be executed as the input is not numeric")
  }
 mean<-mean(data,na.rm = TRUE)
 median<- median(data,na.rm = TRUE)
 print(c(mean,median))
}

#Documenting the function using roxygen() syntax as instructed. 
#'Summary Statistics: Mean and Mode
#'The function created above returns the mean and median of a numeric variable to the user.
#'@param data is the input we will provide for the function to run on. 
#'@param mean is the mean of the numeric variable.
#'@param median is the median of the numeric variable.
#'@return the print command that returns the value of mean and median for the chosen numeric variable or if the input is not numeric, it will return an error as defined.
```

**Exercise 3: Include examples**

**Example 1**
```{r}

#Choosing data from different datasets to check if our function is running. As stated in the function, the first value of the output is mean and the second is the median ie. print(c(mean,median))

#First dataset
vancouver_trees

#Computing the mean and median of the variable 'diameter' using our function MeanandMedian
Example1 <- MeanandMedian(vancouver_trees$diameter)
```
**Example 2**
```{r}
##Second dataset 
apt_buildings

#Example2:Computing the mean and median of the variable 'no_of_elevators' using our function MeanandMedian
Example2 <- MeanandMedian(apt_buildings$no_of_elevators)
```


**Example 3 and 4**
```{r}
##Third dataset
penguins

#Example3:Computing the mean and median of the variable 'bill_length_mm' using our function MeanandMedian
Example3<- MeanandMedian(penguins$bill_length_mm)
```

```{r}
#Example4: Returning an error
#Writing as comment since the Rmd file was not knitting with the error.
#Example4<- MeanandMedian(penguins$island)
```

**Exercise4: Test the function**
```{r}

#Using testthat() and expect_equal(), we expect the function to return the same output as Example3
test_that("mean and median of variable", {
expect_equal(Example3, MeanandMedian(penguins$bill_length_mm)) })

```

```{r}
 #Using testthat() and expect_error() for an input other than numeric.
test_that("Return an error for non-numeric data ", {
expect_error (MeanandMedian(penguins$island))})
```

```{r}
#Using testthat() and expect_error we check for vector of length 0.
test_that("Return an error for vector of length 0 ", {
expect_error (MeanandMedian(penguins$bill_length_mm, numeric(0)))})
```




